[package]
name = "common"
version = "0.1.0"
edition = "2024"

[features]
default = []
# Enable userspace-only impls (aya::Pod, std conversions)
userspace = ["aya"]
# Enable dev-mode for double-NAT testing (not for production)
dev-mode = []

[dependencies]
aya = { version = "0.13.1", optional = true }
siphasher = { version = "1", default-features = false }

[build-dependencies]
toml  = "0.8"
serde = { version = "1", features = ["derive"] }
